//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilliantShiningScriptEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrilliantShiningScriptEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _418 {
            get {
                object obj = ResourceManager.GetObject("_418", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _418ico {
            get {
                object obj = ResourceManager.GetObject("_418ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;script-data&quot;: {
        ///		&quot;key&quot;: &quot;script-data&quot;,
        ///		&quot;file_name&quot;: &quot;ev_script&quot;,
        ///		&quot;full_path&quot;: &quot;Data\\StreamingAssets\\AssetAssistant\\Dpr\\ev_script&quot;,
        ///		&quot;cab_directory&quot;: &quot;CAB-e856180fe48cd419c06715341f9e3f42&quot;,
        ///		&quot;files&quot;: [
        ///			&quot;trainer&quot;
        ///		]
        ///	}
        ///}.
        /// </summary>
        internal static string bundle_constants {
            get {
                return ResourceManager.GetString("bundle_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Id&quot;: 777,
        ///		&quot;Name&quot;: &quot;ACMD_END&quot;,
        ///		&quot;Description&quot;: &quot;Ends a movement script.&quot;,
        ///		&quot;Dummy&quot;: false,
        ///		&quot;Animation&quot;: true,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 811,
        ///		&quot;Name&quot;: &quot;ACMD_NOT&quot;,
        ///		&quot;Description&quot;: &quot;Unused.&quot;,
        ///		&quot;Dummy&quot;: false,
        ///		&quot;Animation&quot;: true,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 1155,
        ///		&quot;Name&quot;: &quot;AC_ANIME_DURATION&quot;,
        ///		&quot;Description&quot;: &quot;(?) Sets the length of the next animation.&quot;,
        ///		&quot;Dummy&quot;: false,
        ///		&quot;Animation&quot;: true,
        ///		&quot;Args&quot;: [
        ///			{
        ///				&quot;TentativeName&quot;: &quot;Time&quot;,
        ///				&quot;Description&quot;: &quot;Time in  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string custom_commands {
            get {
                return ResourceManager.GetString("custom_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string custom_file_names {
            get {
                return ResourceManager.GetString("custom_file_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string custom_flags {
            get {
                return ResourceManager.GetString("custom_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string custom_sys_flags {
            get {
                return ResourceManager.GetString("custom_sys_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string custom_work {
            get {
                return ResourceManager.GetString("custom_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;PathID&quot;: -4159401333858848265,
        ///    &quot;FileName&quot;: &quot;battle_room&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Unused Wireless Battle Room (?)&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -594893302899321786,
        ///    &quot;FileName&quot;: &quot;bg_attr&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Tile-specific Scripts&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -524791092379703435,
        ///    &quot;FileName&quot;: &quot;c01&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Jubilife City&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -696005077699342123,
        ///    &quot;FileName&quot;: &quot;c01fs0101&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string file_names {
            get {
                return ResourceManager.GetString("file_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///		&quot;Id&quot;: 0,
        ///		&quot;Name&quot;:&quot;FH_01&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 1,
        ///		&quot;Name&quot;:&quot;FH_02&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 2,
        ///		&quot;Name&quot;:&quot;FH_03&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 3,
        ///		&quot;Name&quot;:&quot;FH_04&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 4,
        ///		&quot;Name&quot;:&quot;FH_05&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 5,
        ///		&quot;Name&quot;:&quot;FH_06&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 6,
        ///		&quot;Name&quot;:&quot;FH_07&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 7,
        ///		&quot;Name&quot;:&quot;FH_08&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 8,
        ///		&quot;Name&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flags {
            get {
                return ResourceManager.GetString("flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_add {
            get {
                object obj = ResourceManager.GetObject("script_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_base {
            get {
                object obj = ResourceManager.GetObject("script_base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_compile {
            get {
                object obj = ResourceManager.GetObject("script_compile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_info {
            get {
                object obj = ResourceManager.GetObject("script_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_remove {
            get {
                object obj = ResourceManager.GetObject("script_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_save {
            get {
                object obj = ResourceManager.GetObject("script_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_stack {
            get {
                object obj = ResourceManager.GetObject("script_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///		&quot;Id&quot;: 0,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_ARRIVE_START&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 1,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_BAG_GET&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 2,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_PAIR&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 3,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_KAIRIKI&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 4,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_FNOTE_GET&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 5,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_GAME_CLEAR&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 6,
        ///		&quot;Name&quot;:&quot;SYS_FLAG_ONE_STEP&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sys_flags {
            get {
                return ResourceManager.GetString("sys_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///		&quot;Id&quot;: 0,
        ///		&quot;Name&quot;:&quot;LOCALWORK0&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 1,
        ///		&quot;Name&quot;:&quot;LOCALWORK1&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 2,
        ///		&quot;Name&quot;:&quot;LOCALWORK2&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 3,
        ///		&quot;Name&quot;:&quot;LOCALWORK3&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 4,
        ///		&quot;Name&quot;:&quot;LOCALWORK4&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 5,
        ///		&quot;Name&quot;:&quot;LOCALWORK5&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 6,
        ///		&quot;Name&quot;:&quot;LOCALWORK6&quot;,
        ///		&quot;Description&quot;:&quot;&quot;
        ///	},
        ///	{
        ///		&quot;Id&quot;: 7,
        ///		&quot;Name&quot;:&quot;LOCALWORK7&quot;,
        ///		&quot;Descript [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
    }
}
