//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonBDSPEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonBDSPEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _418 {
            get {
                object obj = ResourceManager.GetObject("_418", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _418ico {
            get {
                object obj = ResourceManager.GetObject("_418ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;script-data&quot;: {
        ///		&quot;key&quot;: &quot;script-data&quot;,
        ///		&quot;file_name&quot;: &quot;ev_script&quot;,
        ///		&quot;full_path&quot;: &quot;Data\\StreamingAssets\\AssetAssistant\\Dpr\\ev_script&quot;,
        ///		&quot;cab_directory&quot;: &quot;CAB-e856180fe48cd419c06715341f9e3f42&quot;,
        ///		&quot;files&quot;: [
        ///			&quot;trainer&quot;
        ///		]
        ///	}
        ///}.
        /// </summary>
        internal static string bundle_constants {
            get {
                return ResourceManager.GetString("bundle_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Id&quot;: 777,
        ///		&quot;Name&quot;: &quot;ACMD_END&quot;,
        ///		&quot;Description&quot;: &quot;&quot;,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 811,
        ///		&quot;Name&quot;: &quot;ACMD_NOT&quot;,
        ///		&quot;Description&quot;: &quot;&quot;,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 1155,
        ///		&quot;Name&quot;: &quot;AC_ANIME_DURATION&quot;,
        ///		&quot;Description&quot;: &quot;&quot;,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 805,
        ///		&quot;Name&quot;: &quot;AC_ANM_PAUSE_OFF&quot;,
        ///		&quot;Description&quot;: &quot;&quot;,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 804,
        ///		&quot;Name&quot;: &quot;AC_ANM_PAUSE_ON&quot;,
        ///		&quot;Description&quot;: &quot;&quot;,
        ///		&quot;Args&quot;: []
        ///	},
        ///	{
        ///		&quot;Id&quot;: 775,
        ///		&quot;Name&quot;: &quot;AC_DIR_D&quot;,
        ///		&quot;Description&quot;: &quot;&quot;,
        ///		&quot;Args&quot;: [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_add {
            get {
                object obj = ResourceManager.GetObject("script_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_compile {
            get {
                object obj = ResourceManager.GetObject("script_compile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_remove {
            get {
                object obj = ResourceManager.GetObject("script_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script_save {
            get {
                object obj = ResourceManager.GetObject("script_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
